name: Build CI
on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    paths:
      - '**.md'
      - 'LICENSE'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type: [debug, release]
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build fmt
      run: |
        cd 3rd-party/fmt && mkdir build && cd build && cmake -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE .. && make

    - name: build
      run: make build

    # - name: test ${{ matrix.type }}
    #   run: make test TYPE=${{ matrix.type }}